version: '3.3'
services:
  app:
    build:
      # build from Dockerfile
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./app:/var/www/html

  redis:
    image: mysql/mysql-server:8.0.28

  db:
    image: mysql/mysql-server:8.0.28
    restart: always
    command:
      - --authentication-policy=mysql_native_password
    platform: "linux/amd64"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'